// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhftrkkqdtwkrjmrlqfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoZnRya2txZHR3a3JqbXJscWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjM2NjAsImV4cCI6MjA2Mjg5OTY2MH0.IJLyw4_R8ychNG2Gn_BW1PPKBQX1FZKnW74jLMnftR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);